import {useEffect,useState} from 'react';
export function AccountTools({api,action,load,disabled,settings,job}:any){
 const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<any>(null),[imports,setImports]=useState<any[]>([]),[runs,setRuns]=useState<any[]>([]),[excluded,setExcluded]=useState<number[]>([]);
 const [kind,setKind]=useState('holdings'),[currency,setCurrency]=useState('UNKNOWN'),[mapping,setMapping]=useState<any>({}),[folder,setFolder]=useState(settings.import_folder||'');
 const [complete,setComplete]=useState(false),[accept,setAccept]=useState(false),[included,setIncluded]=useState(true),[replace,setReplace]=useState(false);
 async function refresh(){setImports(await api('/imports'));setRuns(await api('/research/runs'));}
 useEffect(()=>{refresh().catch(()=>{});},[]);
 async function readFile(){
  if(!file)throw new Error('请先选择东方财富导出文件。');
  if(file.size>10*1024*1024)throw new Error('文件最多10MB，请按月份导出。');
  const content=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(new Error('文件读取失败'));r.readAsDataURL(file);});
  const p=await api('/imports/preview','POST',{filename:file.name,content_base64:content,kind,mapping,cost_currency:currency,settlement_currency:currency,amount_includes_fees:included,replace_snapshot:replace});
  setPreview(p);setMapping(p.mapping);setExcluded(p.rows.filter((r:any)=>r.duplicate==='exact').map((r:any)=>r.row));await refresh();
 }
 return <section className="form-section"><h2>东方财富持仓与流水</h2><p>导入后核对持仓与流水。公开行情与研究资料会自动更新；交易变化目前通过新增导出文件更新。</p>
  <label>导入类型<select value={kind} onChange={e=>{setKind(e.target.value);setPreview(null);setMapping({});}}><option value="holdings">当前持仓快照</option><option value="transactions">交割单／资金流水</option></select></label>
  <label>{kind==='holdings'?'券商成本显示币种':'所映射交收金额的币种'}<select value={currency} onChange={e=>setCurrency(e.target.value)}><option value="UNKNOWN">尚未确认</option><option value="CNY">人民币 CNY</option>{kind==='holdings'&&<option value="HKD">港币 HKD</option>}</select></label>
  {kind==='holdings'&&<label className="check-label"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>这是账户全部当前持仓，替换此前持仓（否则只合并所选证券）</label>}
  {kind==='transactions'&&<label className="check-label"><input type="checkbox" checked={included} onChange={e=>setIncluded(e.target.checked)}/>交收金额已包含费用（按导出字段口径核对）</label>}
  <label>导出文件（XLSX、CSV、TSV）<input type="file" accept=".xlsx,.csv,.tsv,.txt" onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null);setMapping({});}}/></label>
  <button className="secondary" disabled={disabled||!file} onClick={()=>action('读取导出文件',readFile)}>读取并预览</button><button className="secondary" disabled={disabled} onClick={()=>action('更新历史行情',()=>job('/history/refresh','获取历史行情、汇率与财务表'))}>获取历史数据</button>
  {preview&&<div className="import-preview"><h3>{preview.filename} · {preview.rows.length} 条有效记录</h3>
   <details><summary>核对或调整字段映射</summary>{Object.keys(preview.mapping).map(k=><label key={k}>{({ticker:'证券代码',name:'名称',exchange:'市场',quantity:'数量',broker_cost:'券商成本',broker_value:'人民币市值',broker_gain:'券商盈亏',day:'日期',kind:'业务类型',amount_cny:'人民币交收金额',fee_cny:'费用',broker_ref:'流水号',currency:'币种',cost_currency:'成本币种'} as any)[k]||k}<select value={mapping[k]||''} onChange={e=>setMapping({...mapping,[k]:e.target.value})}><option value="">未映射</option>{preview.headers.map((h:string)=><option key={h}>{h}</option>)}</select></label>)}<button className="secondary" disabled={disabled||!file} onClick={()=>action('重新解析',readFile)}>按映射重新预览</button></details>
   {preview.issues.map((i:any)=><p className="reading-note" key={i.row}>第 {i.row} 行：{i.message}</p>)}
   <div className="table-scroll"><table><thead><tr><th>导入</th><th>名称／业务</th><th>数量</th><th>成本／金额</th><th>核对</th></tr></thead><tbody>{preview.rows.map((r:any)=><tr key={r.row}><td><input aria-label={'导入第'+r.row+'行'} type="checkbox" checked={!excluded.includes(r.row)} onChange={e=>setExcluded(e.target.checked?excluded.filter(n=>n!==r.row):[...excluded,r.row])}/></td><td>{r.name||r.kind}<small>{r.ticker||r.day} {r.kind}</small></td><td>{r.quantity}</td><td>{r.broker_cost??r.amount_cny??'缺失'}</td><td>{r.duplicate==='suspected'?'疑似重复，请排除或核对':r.duplicate==='exact'?'已导入流水':r.cost_currency==='UNKNOWN'?'成本币种未确认':'待确认'}</td></tr>)}</tbody></table></div>
   {preview.issues.length>0&&<label className="check-label"><input type="checkbox" checked={accept} onChange={e=>setAccept(e.target.checked)}/>仅导入有效记录，异常行暂不入库</label>}
   <button className="primary" disabled={disabled||preview.status==='committed'} onClick={()=>action('确认导入',async()=>{await api('/imports/'+preview.id+'/commit','POST',{exclude_rows:excluded,accept_valid_rows:accept});setPreview(null);await load();await refresh();})}>确认导入选中记录</button>
  </div>}
  <details><summary>已检测到的导出文件</summary>{imports.length?imports.map(i=><p key={i.id}><button className="text-button" disabled={disabled} onClick={()=>action('查看预览',async()=>{const p=await api('/imports/'+i.id);setPreview(p);setMapping(p.mapping);setExcluded([]);})}>{i.filename} · {i.status==='committed'?'已导入':'待核对'}</button></p>):<p>尚未检测到文件。</p>}</details>
  <label>自动检测文件夹（此电脑上的完整路径）<input value={folder} onChange={e=>setFolder(e.target.value)} placeholder="例如 C:\Users\用户名\Documents\交割单"/></label><button className="secondary" disabled={disabled} onClick={()=>action('保存检测文件夹',async()=>{await api('/settings','PUT',{...settings,import_folder:folder});await load();})}>保存文件夹</button>
  <details><summary>完整流水核算模式</summary><p>确认从期初开始的买卖、分红、费用和出入金均已核对，软件还会核对流水与当前快照数量。部分历史不用于完整收益。</p><label className="check-label"><input type="checkbox" checked={complete} onChange={e=>setComplete(e.target.checked)}/>已核对完整历史及现金余额</label><button className="secondary" disabled={disabled||!complete} onClick={()=>action('切换核算模式',async()=>{await api('/portfolio/activate-ledger','POST',{history_complete:true});await load();})}>核对并切换</button></details>
  <details><summary>研究断点与报告状态</summary>{runs.map(r=><p key={r.id}>{r.security_id||'组合'} · {r.status} {r.kind==='company'&&r.status!=='done'&&<button disabled={disabled} onClick={()=>action('继续研究',async()=>{await job('/research/runs/'+r.id+'/resume','继续研究');await refresh();})}>继续未完成章节</button>}</p>)}</details>
 </section>;
}
export function AccountSummary({p,amount}:any){const body=<section className="account-details"><h2>账户核算 · 人民币</h2><p className="meta">{p.coverage}</p><dl className="account-numbers">{[['累计净投入',p.net_investment],['累计损益',p.total_gain],['已实现收益',p.realized_gain],['分红与利息',p.income],['当日账户损益',p.day_gain]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v==null?'历史待完善':amount(v)}</dd></div>)}</dl><p>资金加权年化收益率：{p.money_weighted_return==null?'待核算':p.money_weighted_return+'%'} · 时间加权收益率：{p.time_weighted_return==null?'待核算':p.time_weighted_return+'%'}</p>{p.warnings?.map((w:string)=><p className="help" key={w}>{w}</p>)}</section>;return p.net_investment==null?<details className="account-history"><summary>历史收益 · 待补齐流水</summary>{body}</details>:body;}
export function ResearchChapters({report,amount}:any){return <>
 {report.sections?.map((s:any)=><details key={s.key}><summary>{s.label} · {s.status==='done'?'已完成':'待完成'}</summary><p className="chapter-text">{s.report.summary}</p>{['support','risks','unknowns','assumptions'].map(k=>s.report[k]?.length>0&&<section key={k}><h4>{({support:'分析依据',risks:'反方与风险',unknowns:'资料缺口',assumptions:'假设'} as any)[k]}</h4>{s.report[k].map((x:any,i:number)=><p className="chapter-text" key={i}>{typeof x==='string'?x:x.text}</p>)}</section>)}</details>)}
 {report.risk&&<section><h3>组合情景 · 人民币</h3><p className="help">{report.risk.scenario_note}</p><p>历史共同交易日：{report.risk.observations}。行业仓位：{Object.entries(report.risk.industry_weights).map(([k,v])=>`${k} ${v}%`).join('；')||'待分类'}。</p><p>交易币种仓位：{Object.entries(report.risk.currency_weights).map(([k,v])=>`${k} ${v}%`).join('；')||'待核算'}。现金比例应结合账户快照阅读。</p>{report.risk.risk_contribution&&<details><summary>人民币收益风险贡献与相关性</summary><p className="help">{report.risk.risk_note}</p>{Object.entries(report.risk.risk_contribution).map(([k,v])=><p key={k}>{k} · 日波动贡献 {(Number(v)*100).toFixed(3)}%</p>)}<div className="table-scroll"><table><thead><tr><th>相关系数</th>{Object.keys(report.risk.correlation).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{Object.entries(report.risk.correlation).map(([k,values]:any)=><tr key={k}><th>{k}</th>{Object.keys(report.risk.correlation).map(j=><td key={j}>{Number(values[j]).toFixed(3)}</td>)}</tr>)}</tbody></table></div></details>}{report.risk.scenarios.map((s:any)=><p key={s.name}>{s.name}：可能减少 {amount(s.loss_cny)} 元</p>)}{report.risk.warnings.map((w:string)=><p className="help" key={w}>{w}</p>)}</section>}
 {report.as_of&&<p className="meta">分析快照时间：{new Date(report.as_of).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}（北京时间）</p>}
 </>}
