import React,{useRef,useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Leaf,BookOpen,Search,BriefcaseBusiness,ArrowRight,Check,ChevronDown,FileText,LoaderCircle,Bookmark,Clock,ExternalLink} from 'lucide-react';
import './Demo.css';
import {DemoLab} from './DemoLab';
const chapters=[
 ['业务与盈利','看清收入从哪里来，再看利润留在哪里','示例研究把成熟业务、服务收入与新业务分开讨论。收入规模、利润率和现金投入需要一起看，不能仅凭某项业务增长就判断整体盈利改善。'],
 ['历史财务','利润增长是否变成了现金','重点复查经营现金流、库存周转与资本开支。如果利润增长而现金回收持续偏弱，需要进一步查明原因。本 Demo 不提供真实财务数字。'],
 ['最新变化','新事件如何改变原来的判断','模拟事件：公司发布经营进展。先与历史趋势对比，再判断它是否改变盈利能力。单次发布不能代替连续经营证据。'],
 ['竞争与行业','竞争优势能否持续','观察产品竞争、价格变化和供应链成本。行业政策与同业消息作为背景资料，需要区分公司事实与行业推论。'],
 ['估值与情景','价格背后的假设是什么','正式报告应展示计算输入、估值日期和不同假设的结果。这里仅展示阅读布局，不提供目标价或买卖建议。'],
 ['风险与反方','什么证据会让我们改变看法','如果核心业务利润下降、现金投入超出预期或新业务进展不及假设，需要重新检查持有理由。反方证据与支持证据同样重要。']];
const news=[
 {id:1,kind:'公司公告',source:'公司投资者关系 / 港交所',time:'09:20',company:'小米集团',title:'模拟公告：公司发布经营进展，需对照盈利与现金投入',reason:'与你关注的公司直接相关。优先看经营数据与原有假设是否一致。',detail:'这是一条虚构公告。正式接入后，此处展示公告原文摘要、发布日期、采集时间，以及与已有研究的差异。',priority:true},
 {id:2,kind:'官方发布',source:'监管部门官方网站（拟接入）',time:'08:45',company:'行业背景',title:'模拟政策：行业新规发布，关注适用范围与实施时间',reason:'政策可能影响行业，但尚不能据此判断某家公司的业绩。',detail:'正式内容应区分政策原文、解读和公司适用性。需要核对发布机构、适用范围及实施日期。',priority:false},
 {id:3,kind:'媒体报道',source:'新华社 / 财经媒体（拟接入）',time:'08:10',company:'腾讯控股',title:'模拟报道：行业需求变化，值得与公司披露交叉核对',reason:'提供行业背景。报道中的判断需要回到公司披露与原始数据核实。',detail:'媒体知名不等于每项结论均已验证。正式新闻将展示原始报道链接，区分报道事实、引述与观点。',priority:false}];
function Demo(){
 const [page,setPage]=useState('research'),[company,setCompany]=useState('小米集团'),[query,setQuery]=useState(''),[status,setStatus]=useState('idle'),[tab,setTab]=useState(0),[filter,setFilter]=useState('全部'),[expanded,setExpanded]=useState<number|null>(null),[saved,setSaved]=useState(false),[briefVersion,setBriefVersion]=useState(0),[homeNotice,setHomeNotice]=useState(''),[question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[archive,setArchive]=useState<string[]>(['腾讯控股']);
 const reportRef=useRef<HTMLElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 useEffect(()=>{window.scrollTo(0,0)},[page]);
 function showReport(){setStatus('done');setTab(0);setArchive(v=>Array.from(new Set([company,...v])));requestAnimationFrame(()=>{reportRef.current?.scrollIntoView({behavior:'auto',block:'start'});reportRef.current?.focus({preventScroll:true})})}
 function analyze(){setStatus('loading');setSaved(false);timer.current=setTimeout(showReport,1600)}
 function choose(v:string){if(timer.current)clearTimeout(timer.current);setCompany(v);setStatus('idle');setSaved(false);setAnswer('')}
 return <div className="demo-shell"><aside className="demo-sidebar"><a className="demo-brand" href="#" onClick={e=>{e.preventDefault();setPage('research')}}><Leaf size={28}/><span>投资信息台<small>看清信息，自己判断</small></span></a><nav aria-label="主要导航">{[['home','今日关注',BookOpen],['research','公司研究',Search],['portfolio','我的持仓',BriefcaseBusiness]].map(([key,label,Icon]:any)=><button key={key} aria-pressed={page===key} className={page===key?'selected':''} onClick={()=>setPage(key)}><Icon size={21}/>{label}{page===key&&<ArrowRight size={16}/>}</button>)}</nav><button className="lab-maintain" aria-pressed={page==='settings'} onClick={()=>setPage('settings')}>维护设置<ArrowRight size={16}/></button><div className="demo-side-note"><p>更少寻找，<br/>更容易读懂。</p><small>本页只演示阅读与操作。<br/>不连接账户或付费服务。</small></div></aside><main className="demo-main"><header className="demo-top"><span>阅读体验 Demo</span><span className="demo-label">全部为模拟内容</span></header>
 {page==='research'&&<><div className="demo-heading"><h1>公司研究</h1><p>先看结论，再看依据。生成的报告就在这里。</p></div><section className="demo-controls" aria-label="选择研究公司"><form onSubmit={e=>{e.preventDefault();if(query.trim()){choose(query.trim());setQuery('')}}}><Search size={21}/><input aria-label="公司名称或股票代码" placeholder="输入公司名称或代码，体验切换" value={query} onChange={e=>setQuery(e.target.value)}/><button>查找公司</button></form><div className="demo-company-row"><label>当前公司<select value={company} onChange={e=>choose(e.target.value)}>{Array.from(new Set(['小米集团','腾讯控股','中芯国际','京东物流',company])).map(x=><option key={x}>{x}</option>)}</select></label><button className="demo-primary" disabled={status==='loading'} onClick={analyze}>{status==='loading'?<><LoaderCircle className="demo-spin" size={19}/>正在整理模拟报告</>:<>{status==='done'?'重新体验分析':'分析这家公司'}<ArrowRight size={19}/></>}</button></div></section>
 {status==='idle'&&<section className="demo-result-placeholder"><FileText size={32}/><div><h2>分析结果会出现在这里</h2><p>点击「分析这家公司」，体验报告直接展开。无需到页面底部寻找。</p></div><button onClick={showReport}>直接看示例<ArrowRight size={17}/></button></section>}
 {status==='loading'&&<section className="demo-loading" role="status"><LoaderCircle className="demo-spin" size={25}/><h2>正在整理 {company} 的示例研究</h2><p>模拟流程：资料梳理 → 重点提炼 → 展示完整报告</p></section>}
 {status==='done'&&<section className="demo-report" ref={reportRef} tabIndex={-1} aria-label="最新公司研究报告"><div className="demo-report-top"><span><Check size={17}/>示例报告已生成</span><button className="demo-save" onClick={()=>setSaved(!saved)}><Bookmark size={17}/>{saved?'已标记稍后阅读':'稍后阅读'}</button></div><h2>{company}：先看盈利质量，再看增长</h2><p className="demo-report-meta">模拟研究 · 六个章节 · 不含真实行情或财务结论</p><div className="demo-summary"><h3>先读这段</h3><p>示例判断：值得持续观察的是<mark>核心业务的盈利稳定性</mark>与<mark>新业务的现金投入</mark>。业务增长本身还不够，需要与利润和现金流相互印证。</p></div><div className="demo-takeaways"><div><strong>值得关注</strong><p>业务结构与利润来源是否改善。</p></div><div><strong>主要风险</strong><p>投入增加，但现金回收落后。</p></div><div><strong>下一步核对</strong><p>最新披露与历史趋势是否一致。</p></div></div><div className="demo-report-layout"><nav className="demo-chapter-nav" aria-label="报告章节"><h3>完整报告</h3>{chapters.map((c,i)=><button key={c[0]} aria-pressed={tab===i} className={tab===i?'selected':''} onClick={()=>setTab(i)}>{c[0]}{tab===i&&<ArrowRight size={16}/>}</button>)}</nav><article className="demo-chapter"><h3>{chapters[tab][1]}</h3><p>{chapters[tab][2]}</p><div className="demo-point"><strong>本节重点</strong><p>{tab===0?'把增长、盈利与现金投入放在一起判断。':tab===5?'明确哪些新证据会使原有论点失效。':'先核对事实，再解释影响；信息不足就明确保留缺口。'}</p></div><details key={tab}><summary>查看依据与资料缺口<ChevronDown size={17}/></summary><p>下面为虚构底稿，展示正式报告的证据阅读方式，不是公司真实披露。</p><div className="lab-source"><strong>模拟年度经营报告 · 2025年度</strong><p>示例：收入由100增至128亿元，增长28%；经营现金流20亿元、资本开支12亿元。数字仅用于演示结构。</p><small>来源身份：公司披露示例 · 尚未核验 · 无真实原文链接</small></div><div className="lab-source"><strong>模拟经营发布 · 2026年10月</strong><p>演示最新事件如何与历史经营趋势对照。资料缺口：同行可比口径、分部现金流。</p><small>来源身份：投资者关系材料示例 · 尚未核验</small></div></details><button className="demo-next" onClick={()=>setTab((tab+1)%chapters.length)}>{tab===5?'返回业务与盈利':'阅读下一节'}<ArrowRight size={17}/></button></article></div><section className="lab-followup"><h3>继续问这家公司</h3><div className="lab-actions">{['现金流有什么风险？','什么情况需要重新判断？'].map(q=><button key={q} onClick={()=>{setQuestion(q);setAnswer('模拟追问回答：先核对经营现金流与资本开支，再检查最新变化是否推翻原来的假设。结论要与证据对应，缺口继续保留。')}}>{q}</button>)}</div><form onSubmit={e=>{e.preventDefault();if(question.trim())setAnswer('模拟回答：你的问题是「'+question+'」。示例中建议把盈利、现金回收与新业务投入一起复查，并回到来源核对。这是交互演示，不是针对该公司的真实判断。')}}><input aria-label="研究追问" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="继续问一个问题" required/><button>提交模拟追问<ArrowRight size={16}/></button></form>{answer&&<p role="status">{answer}</p>}</section></section>}
 <section className="demo-history"><h2>以前的研究</h2><p>虚拟历史记录，点击可回看。刷新后回到内置示例。</p><div className="lab-actions">{archive.map(n=><button key={n} onClick={()=>{choose(n);setStatus('done');setTab(0);requestAnimationFrame(()=>reportRef.current?.scrollIntoView({block:'start'}))}}>{n} · 示例研究<FileText size={16}/></button>)}</div></section></>}
 {page==='home'&&<><div className="demo-heading"><h1>今天，先看重要的事。</h1><p>公司公告、官方发布与可信媒体，同处一个阅读入口。</p></div><section className="demo-digest"><div className="demo-digest-header"><h2>今日重点{briefVersion>0?' · 已模拟更新':''}</h2><span><Clock size={16}/>示例更新于 09:30</span></div><p>模拟简报：有一条公司动态值得优先核对，另外两条提供政策与行业背景。<strong>来源可靠程度与事件影响分开判断。</strong></p><div className="lab-actions"><button onClick={()=>{setFilter('重点');setExpanded(1)}}>看重点动态<ArrowRight size={17}/></button><button onClick={()=>{setBriefVersion(v=>v+1);setHomeNotice('已重新整理模拟简报。正式软件会按日期与事件去重。')}}>整理模拟简报</button><button onClick={()=>{setHomeNotice('已模拟检查关注公司，新增事件已展示；无实质变化时不重复提醒。')}}>检查新增资料</button></div>{homeNotice&&<p role="status" className="lab-notice">{homeNotice}</p>}</section><div className="demo-news-heading"><h2>新闻与公告</h2><p>展示来源身份，不把媒体报道直接当成公司事实。</p></div><div className="demo-filters" role="group" aria-label="新闻筛选">{['全部','重点','公司公告','官方发布','媒体报道'].map(x=><button key={x} aria-pressed={filter===x} className={filter===x?'selected':''} onClick={()=>{setFilter(x);setExpanded(null)}}>{x}</button>)}</div><div className="demo-news-list">{news.filter(n=>filter==='全部'||filter==='重点'&&n.priority||n.kind===filter).map(n=><article key={n.id} className="demo-news"><div className="demo-news-meta"><span>{n.kind}</span>{n.priority&&<strong>优先阅读</strong>}<time>{n.time} · 模拟时间</time></div><h3>{n.title}</h3><p className="demo-relevance"><strong>为什么关注</strong>{n.reason}</p><div className="demo-news-bottom"><span>{n.source}<small>来源类型示例 · 未进行真实检索</small></span><button aria-expanded={expanded===n.id} onClick={()=>setExpanded(expanded===n.id?null:n.id)}>{expanded===n.id?'收起详情':'查看详情'}<ArrowRight size={17}/></button></div>{expanded===n.id&&<div className="demo-news-detail"><h4>事件与影响分开读</h4><p>{n.detail}</p><p><strong>来源核验：</strong>演示内容，未核验；没有真实原文链接。</p><button onClick={()=>{choose(n.company==='行业背景'?'小米集团':n.company);setPage('research')}}>进入公司研究<ArrowRight size={17}/></button></div>}</article>)}</div></>}
 <DemoLab page={page} research={name=>{choose(name);setPage('research')}}/>
 <footer className="demo-footer">所有新闻、研究观点和时间均为模拟，不构成实际投资分析。<a href="http://127.0.0.1:8765/" target="_blank" rel="noreferrer">打开现有软件<ExternalLink size={14}/></a></footer></main></div>
}
createRoot(document.getElementById('root')!).render(<Demo/>);
