import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,RefreshCw,Eye,EyeOff,Check,LoaderCircle,Download,Bell,Settings2,Plus,FileText} from 'lucide-react';
export type Holding={code:string;name:string;sector:string;qty:number;cost:number;price:number;previous:number};
export const seed:Holding[]=[
 {code:'01810',name:'小米集团',sector:'消费电子',qty:1000,cost:35,price:40,previous:39},
 {code:'00700',name:'腾讯控股',sector:'互联网服务',qty:200,cost:450,price:500,previous:490},
 {code:'00981',name:'中芯国际',sector:'半导体',qty:2000,cost:60,price:50,previous:51},
 {code:'02618',name:'京东物流',sector:'物流',qty:5000,cost:12,price:15,previous:14.8}];
export const money=(v:number)=>v.toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
// 演示数值转为人民币分后加总，避免显示结果因浮点加总而不一致。
export const value=(h:Holding,p=h.price,fx=.92)=>Math.round(h.qty*p*fx*100)/100;
export function demoTotals(rows:Holding[],cash=50200,fx=.92){const sum=(a:number[])=>a.reduce((s,n)=>s+Math.round(n*100),0)/100;const securities=sum(rows.map(h=>value(h,h.price,fx))),cost=sum(rows.map(h=>value(h,h.cost,.92))),previous=sum(rows.map(h=>value(h,h.previous,fx)));return {securities,cost,total:sum([securities,cash]),gain:sum([securities,-cost]),daily:sum([securities,-previous]),cash};}
const inputFlows=[['2026-08-03','入金','账户','330000.00'],['2026-08-04','买入','小米集团','-32200.00'],['2026-08-04','买入','腾讯控股','-82800.00'],['2026-08-05','买入','中芯国际','-110400.00'],['2026-08-05','买入','京东物流','-55200.00'],['2026-09-15','分红','腾讯控股','1000.00'],['2026-09-15','费用','账户','-200.00']];
function download(name:string,text:string){const u=URL.createObjectURL(new Blob([text],{type:'application/json;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
type Props={page:string;research:(name:string)=>void};
export function DemoLab({page,research}:Props){
 const [rows,setRows]=useState(seed.map(h=>({...h}))),[hidden,setHidden]=useState(false),[cash,setCash]=useState(50200),[fx,setFx]=useState(.92),[tick,setTick]=useState(0),[quoteTime,setQuoteTime]=useState('2026-10-05 10:00:00'),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[report,setReport]=useState<{rows:Holding[];cash:number;fx:number;time:string}|null>(null),[riskTab,setRiskTab]=useState('组合重点'),[preview,setPreview]=useState(false),[importDone,setImportDone]=useState(false),[ledger,setLedger]=useState(true),[history,setHistory]=useState(false),[scenario,setScenario]=useState('证券下跌10%'),[custom,setCustom]=useState(10),[push,setPush]=useState(false),[auto,setAuto]=useState(true),[eventAI,setEventAI]=useState(false),[kimi,setKimi]=useState(true),[budget,setBudget]=useState(20),[used,setUsed]=useState(.84),[notifyRows,setNotifyRows]=useState<string[]>([]),[configSaved,setConfigSaved]=useState(false),[folder,setFolder]=useState('C:\\投资研究\\东方财富导出'),[quoteSource,setQuoteSource]=useState('公开延迟行情'),[edit,setEdit]=useState(''),[quantity,setQuantity]=useState(''),[draft,setDraft]=useState(false),[resumed,setResumed]=useState(false),[offline,setOffline]=useState(false);
 const timeouts=useRef<ReturnType<typeof setTimeout>[]>([]),ref=useRef<HTMLElement>(null);
 useEffect(()=>()=>timeouts.current.forEach(clearTimeout),[]);
 useEffect(()=>{setNotice('')},[page]);
 function task(label:string,run:()=>void){setBusy(label);setNotice('');timeouts.current.push(setTimeout(()=>{run();setBusy('')},900))}
 function freeze(){if(offline){setNotice('模拟断网，组合联网分析暂停；本地估值与情景报告仍可阅读。');return}if(!kimi){setNotice('模拟连接已断开，请到维护页点击模拟连接。');return}if(used+.35>budget){setNotice('模拟预算不足，本地行情与核算仍可用。提高模拟预算后再生成报告。');return}task('正在模拟组合研究',()=>{setReport({rows:rows.map(h=>({...h})),cash,fx,time:quoteTime});setRiskTab('组合重点');setUsed(v=>Math.round((v+.35)*100)/100);requestAnimationFrame(()=>{ref.current?.scrollIntoView({block:'start'});ref.current?.focus({preventScroll:true})})})}
 const totals=demoTotals(rows,cash,fx), r=report?demoTotals(report.rows,report.cash,report.fx):totals;
 const sumLoss=(pct:number)=>r.securities*pct/100, largest=report?[...report.rows].sort((a,b)=>value(b,b.price,report.fx)-value(a,a.price,report.fx))[0]:rows[0];
 const scenarios=[['证券下跌10%',sumLoss(10)],['证券下跌20%',sumLoss(20)],['最大持仓下跌20%',largest?value(largest,largest.price,report?.fx||fx)*.2:0],['港币相对人民币贬值5%',sumLoss(5)],['自定义证券跌幅',sumLoss(custom)]] as [string,number][];
 const amount=(n:number)=>hidden?'••••••':money(n);
 if(page!=='portfolio'&&page!=='settings')return null;
 return <><div className="demo-heading"><h1>{page==='portfolio'?'我的持仓':'维护设置'}</h1><p>{page==='portfolio'?'四只虚拟港股，一份可核对的账户。点击行情与分析，感受完整流程。':'所有设置、连接和推送均为模拟。这里不输入真实密钥。'}</p></div>{notice&&<div className="lab-notice" role="status"><Check size={19}/>{notice}</div>}{busy&&<div className="lab-notice" role="status"><LoaderCircle size={19} className="demo-spin"/>{busy}…</div>}
 {page==='portfolio'&&<>{offline&&<div className="lab-notice" role="status">模拟断网：保留最后成功报价，当前数据可能过期。</div>}<div className="lab-actions"><button onClick={()=>setHidden(!hidden)}>{hidden?<Eye size={18}/>:<EyeOff size={18}/>} {hidden?'显示演示金额':'隐藏演示金额'}</button><button disabled={!!busy} onClick={()=>{if(offline){setNotice('模拟网络不可用：最后报价与金额保留，没有冒充更新成功。');return}task('更新虚拟行情',()=>{const next=tick+1;setTick(next);setRows(v=>v.map((h,i)=>({...h,price:Math.round((h.price+(i%2===0?.2:-.1))*100)/100})));setQuoteTime(`2026-10-05 10:${String(next).padStart(2,'0')}:00`);setNotice('虚拟报价已变化，账户已重新计算。已生成报告仍保留分析时的快照。')})}}><RefreshCw size={18}/>更新行情</button><button className="demo-primary" disabled={!!busy||rows.length===0} onClick={freeze}>分析我的持仓<ArrowRight size={18}/></button></div>
 <section className="lab-account"><h2>虚拟账户概览 <small>人民币 CNY</small></h2><dl className="lab-numbers">{[['当前总资产',totals.total],['证券市值',totals.securities],['现金',cash],['当前持仓成本',totals.cost],['持仓浮盈亏',totals.gain],['当日损益',totals.daily]].map(([label,n])=><div key={label}><dt>{label}</dt><dd>{amount(Number(n))}</dd></div>)}</dl><p>模拟报价时间：{quoteTime}（北京时间） · 来源：{quoteSource} · 延迟15分钟（模拟设定）</p><p>模拟参考汇率：1 HKD = {fx.toFixed(4)} CNY。现金不随股票报价变化。当日损益假设当日无交易、出入金且汇率不变。</p></section>
 <section className="lab-holdings"><h2>持仓明细 <small>所有报价、成本和数量均虚构</small></h2><div className="lab-table"><table><thead><tr><th>证券</th><th>持有数量</th><th>港元报价 / 成本</th><th>人民币市值</th><th>浮盈亏</th><th>仓位</th><th>操作</th></tr></thead><tbody>{rows.map(h=><tr key={h.code}><td><strong>{h.name}</strong><small>HK · {h.code} · {h.sector}</small></td><td>{hidden?'••••':h.qty.toLocaleString()}</td><td>{h.price.toFixed(2)}<small>核算成本 {hidden?'••••':h.cost.toFixed(2)} HKD</small>{importDone&&h.code==='00981'&&<small>券商显示成本 {hidden?'••••':'-3.000'} CNY（原样保留）</small>}</td><td>{amount(value(h,h.price,fx))}</td><td className={value(h,h.price,fx)>=value(h,h.cost,.92)?'lab-gain':'lab-loss'}>{amount(value(h,h.price,fx)-value(h,h.cost,.92))}<small>{((value(h,h.price,fx)/value(h,h.cost,.92)-1)*100).toFixed(2)}%</small></td><td>{(value(h,h.price,fx)/totals.total*100).toFixed(1)}%</td><td><button onClick={()=>research(h.name)}>研究</button><button onClick={()=>{setEdit(h.code);setQuantity(String(h.qty));setDraft(true)}}>调整</button></td></tr>)}</tbody></table></div>{draft&&<form className="lab-edit" onSubmit={e=>{e.preventDefault();const n=Number(quantity);if(!Number.isInteger(n)||n<1){setNotice('请输入正整数数量。');return}setRows(v=>v.map(h=>h.code===edit?{...h,qty:n}:h));setLedger(false);setDraft(false);setNotice('已修改虚拟快照，历史本金与累计收益暂不展示，避免沿用不完整的流水。')}}><label>调整虚拟持仓数量<input type="number" min="1" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label><button>保存虚拟调整</button><button type="button" onClick={()=>setDraft(false)}>取消</button></form>}</section>
 <details className="lab-details"><summary>本金、收益与资金流水</summary><p>{ledger?(hidden?'虚拟完整流水模式：买入、分红和费用金额已隐藏。':'虚拟完整流水模式：买入合计280,600元，分红1,000元，费用200元。'):'虚拟快照模式：修改持仓后，历史流水尚未核对。'}</p><dl className="lab-numbers"><div><dt>累计净投入</dt><dd>{ledger?amount(330000):'待核对'}</dd></div><div><dt>累计损益</dt><dd>{ledger?amount(totals.total-330000):'待核对'}</dd></div><div><dt>累计收益比例</dt><dd>{ledger?((totals.total/330000-1)*100).toFixed(2)+'%':'待核对'}</dd></div></dl>{ledger&&<dl className="lab-numbers"><div><dt>年化资金加权收益率（模拟）</dt><dd>{((Math.pow(totals.total/330000,365/63)-1)*100).toFixed(2)}%</dd></div><div><dt>期间时间加权收益率（模拟）</dt><dd>{((totals.total/330000-1)*100).toFixed(2)}%</dd></div></dl>}<p>收益比例为累计损益 ÷ 净投入。示例假设8月3日一次入金，此后无外部出入金；下方年化采用63天期间，仅用于虚拟核算。</p><div className="lab-table"><table><thead><tr><th>日期</th><th>业务</th><th>证券</th><th>人民币现金变化</th></tr></thead><tbody>{inputFlows.map((row,i)=><tr key={i}>{row.map((x,j)=><td key={j}>{hidden&&j===3?'••••••':x}</td>)}</tr>)}</tbody></table></div></details>
 <section className="lab-report-placeholder"><h2>{report?'本次组合研究':'组合研究会显示在这里'}</h2>{!report&&<p>点击上方「分析我的持仓」，查看集中度、盈亏贡献、情景与复查事项。</p>}</section>
 {report&&<section className="demo-report" ref={ref} tabIndex={-1} aria-label="模拟组合研究报告"><div className="demo-report-top"><span><Check size={17}/>模拟组合报告已生成</span><span>冻结于 {report.time}</span></div><h2>你的共同风险，比股票数量更重要。</h2><p className="demo-report-meta">根据虚拟仓位计算 · 模拟判断 · 本次金额与快照保持一致</p><div className="demo-summary"><h3>先读这段</h3><p>最大的两项股票仓位占账户 <mark>{([...report.rows].sort((a,b)=>value(b,b.price,report.fx)-value(a,a.price,report.fx)).slice(0,2).reduce((s,h)=>s+value(h,h.price,report.fx),0)/r.total*100).toFixed(1)}%</mark>。这些公司业务不同，但示例研究认为它们可能共同受到经济需求与市场风险偏好的影响。另有 <mark>{(report.cash/r.total*100).toFixed(1)}% 现金</mark>，可缓冲股票整体下跌。</p></div><div className="demo-filters" aria-label="组合报告章节">{['组合重点','盈亏与仓位','压力情景','历史相关性','复查清单'].map(t=><button key={t} aria-pressed={riskTab===t} className={riskTab===t?'selected':''} onClick={()=>setRiskTab(t)}>{t}</button>)}</div>
 {riskTab==='组合重点'&&<article className="lab-reading"><h3>先复查中芯国际，再检查共同暴露</h3><p>示例中的中芯国际浮亏，需要区分价格回撤与经营论点变化；不能因为亏损最大就认定应该卖出。小米与腾讯的盈利质量、行业竞争也应定期复查。</p><h3>港元报价，人民币核算</h3><p>所有证券以港元报价、折算成人民币估值。汇率变化会影响账户人民币市值；历史交收仍应以人民币流水为准。</p></article>}
 {riskTab==='盈亏与仓位'&&<div className="lab-reading">{report.rows.map(h=><div className="lab-contribution" key={h.code}><span>{h.name}<small>{h.sector}</small></span><div><div className="lab-bar"><span style={{width:`${value(h,h.price,report.fx)/r.total*100}%`}}/></div><small>仓位 {(value(h,h.price,report.fx)/r.total*100).toFixed(1)}% · 浮盈亏 {amount(value(h,h.price,report.fx)-value(h,h.cost,.92))} CNY</small></div></div>)}</div>}
 {riskTab==='压力情景'&&<article className="lab-reading"><h3>假设发生时，金额会怎样变化？</h3><div className="lab-scenario-controls"><label>选择情景<select value={scenario} onChange={e=>setScenario(e.target.value)}>{scenarios.map(([s])=><option key={s}>{s}</option>)}</select></label>{scenario==='自定义证券跌幅'&&<label>跌幅（%）<input type="number" min="0" max="100" value={custom} onChange={e=>setCustom(Math.min(100,Math.max(0,Number(e.target.value))))}/></label>}</div><dl className="lab-numbers"><div><dt>假设损失（人民币）</dt><dd>{amount(scenarios.find(x=>x[0]===scenario)?.[1]||0)}</dd></div><div><dt>情景后账户资产</dt><dd>{amount(r.total-(scenarios.find(x=>x[0]===scenario)?.[1]||0))}</dd></div></dl><p>这是基于冻结仓位的算术假设，不是预测。不计后续买卖、费用或分红；股票下跌与汇率情景分开计算。</p></article>}
 {riskTab==='历史相关性'&&<article className="lab-reading"><h3>{history?'历史覆盖模拟已完成':'暂不输出统计风险结论'}</h3><p>{history?'演示状态：已模拟获取120个共同交易日。下方矩阵为人为设置的虚拟相关性，用来体验阅读，不是市场数据计算结果。':'当前只有虚拟持仓和报价，没有可核验的历史收益序列。你仍可使用集中度与情景计算。'}</p>{history&&<div className="lab-table"><table><thead><tr><th>虚拟相关性</th>{seed.map(h=><th key={h.code}>{h.name}</th>)}</tr></thead><tbody>{[[1,.42,.57,.35],[.42,1,.3,.51],[.57,.3,1,.22],[.35,.51,.22,1]].map((a,i)=><tr key={i}><th>{seed[i].name}</th>{a.map((v,j)=><td key={j}>{v.toFixed(2)}</td>)}</tr>)}</tbody></table><p>风险贡献示例：小米12%、腾讯29%、中芯39%、京东物流20%。这些比例只演示布局，未经风险模型计算。</p></div>}<button disabled={!!busy} onClick={()=>task('模拟获取历史数据',()=>{setHistory(true);setNotice('历史资料覆盖状态已切换为模拟完成；没有联网拉取行情。')})}>体验获取历史数据</button></article>}
 {riskTab==='复查清单'&&<article className="lab-reading"><h3>持仓理由需要哪些证据？</h3>{report.rows.map(h=><div className="lab-check-row" key={h.code}><span><strong>{h.name}</strong><small>核对最新经营数据、盈利质量与原有假设。</small></span><button onClick={()=>research(h.name)}>研究这家公司<ArrowRight size={17}/></button></div>)}</article>}
 </section>}</>}
 {page==='settings'&&<><section className="lab-settings"><h2>服务连接与费用</h2><p>不用填真实账号。点击按钮即可模拟连接和失败恢复。</p><div className="lab-check-row"><span><strong>Kimi 开放平台</strong><small>{kimi?'模拟已连接，可体验研究':'模拟未连接，研究连接待恢复'}</small></span><button onClick={()=>{setKimi(!kimi);setNotice(kimi?'已模拟断开。真实软件中需要配置API密钥。':'已模拟连接，不会发送网络请求。')}}>{kimi?'模拟断开':'模拟连接'}</button></div><div className="lab-edit"><label>模拟月预算（元）<input type="number" min="1" max="200" value={budget} onChange={e=>{setBudget(Math.max(1,Math.min(200,Number(e.target.value))));setConfigSaved(false)}}/></label><button onClick={()=>{setConfigSaved(true);setNotice('预算设置仅在当前demo有效，没有修改真实软件。')}}>保存模拟设置</button></div><p>{configSaved?'设置已模拟保存。':'可调整预算，体验费用显示。'} 虚拟费用 ¥{money(used)} / ¥{money(budget)}；模拟余量 ¥{money(Math.max(0,budget-used))}。</p><details><summary>查看模拟费用明细</summary><p>模型与工具虚拟历史费用：¥0.84；每次演示组合分析增加¥0.35，仅用于界面展示。实际计费为0元。</p></details></section>
 <section className="lab-settings"><h2>导入东方财富文件</h2><p>用内置虚拟文件体验预览、重复记录核对和确认导入，不读取你电脑上的真实文件。</p><div className="lab-actions"><button onClick={()=>{setPreview(true);setImportDone(false)}}><FileText size={18}/>载入虚拟导出文件</button><button disabled={!!busy} onClick={()=>task('检测虚拟导入文件夹',()=>{setPreview(true);setNotice('已发现虚拟文件「演示持仓.csv」，生成预览，尚未记账。')})}>模拟检测新文件</button></div>{preview&&<div className="lab-import"><h3>导入预览 · 演示持仓.csv</h3><p>4条有效记录，另1条重复记录已标注。证券代码保留前导零；负券商成本仅作原样展示。窄屏可横向滑动查看导入状态。</p><div className="lab-table"><table><thead><tr><th>代码</th><th>名称</th><th>数量</th><th>券商成本 / CNY</th><th>状态</th></tr></thead><tbody>{seed.map((h,i)=><tr key={h.code}><td>{h.code}</td><td>{h.name}</td><td>{h.qty}</td><td>{i===2?'-3.000':(h.cost*.92).toFixed(3)}</td><td>可导入</td></tr>)}<tr><td>01810</td><td>小米集团</td><td>1000</td><td>32.200</td><td>疑似重复 · 演示排除</td></tr></tbody></table></div><button className="demo-primary" disabled={importDone} onClick={()=>{setRows(seed.map(h=>({...h})));setCash(50200);setFx(.92);setLedger(false);setImportDone(true);setTick(0);setQuoteTime('2026-10-05 10:00:00');setNotice('已将4条虚拟持仓载入demo。重复记录不累加，账户现在使用快照模式。')}}>{importDone?'虚拟导入已完成':'确认导入4条虚拟持仓'}</button></div>}<label className="lab-wide-label">虚拟导入文件夹<input value={folder} onChange={e=>setFolder(e.target.value)}/></label><button onClick={()=>setNotice('文件夹路径已在demo中记录。没有访问或监视实际目录。')}>保存虚拟文件夹</button><label className="lab-checkbox"><input type="checkbox" checked={ledger} onChange={e=>{if(e.target.checked&&JSON.stringify(rows.map(h=>[h.code,h.qty]))!==JSON.stringify(seed.map(h=>[h.code,h.qty]))){setNotice('虚拟数量与示例流水不一致。先恢复演示持仓，再切换完整流水模式。');return}setLedger(e.target.checked)}}/>模拟完整流水已核对</label></section>
 <section className="lab-settings"><h2>行情与自动收集</h2><div className="lab-edit"><label>模拟行情来源<select value={quoteSource} onChange={e=>setQuoteSource(e.target.value)}><option>公开延迟行情</option><option>富途OpenD（模拟权限）</option></select></label><label>参考汇率 HKD/CNY<input type="number" min="0.1" max="2" step="0.0001" value={fx} onChange={e=>{setFx(Math.max(.1,Math.min(2,Number(e.target.value))));setLedger(false)}}/></label></div><label className="lab-checkbox"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>定时收集（模拟每30分钟；北京时间08:00日报）</label><label className="lab-checkbox"><input type="checkbox" checked={eventAI} onChange={e=>setEventAI(e.target.checked)}/>新增重大资料时更新研究论点（模拟）</label><button disabled={!!busy} onClick={()=>task('模拟收集资料',()=>setNotice('已模拟收集2份公司披露与1条官方新闻；新增重点已在今日关注示例中展示。'))}>立即体验资料收集</button><p>{auto?'已模拟启用定时计划；关闭demo页面后不会运行。':'模拟任务已暂停。'} 这里不创建真实后台定时器。</p><button disabled={!!busy} onClick={()=>{setOffline(!offline);setNotice(offline?'模拟网络已恢复，可返回持仓刷新报价。':'已模拟断网。返回持仓会看到过期报价提示，刷新与联网研究保留失败状态。')}}>{offline?'恢复模拟网络':'模拟断网'}</button></section>
 <section className="lab-settings"><h2>微信提醒</h2><p>模拟接收人：演示爸爸。这里不会向任何真实微信账号发消息。</p><label className="lab-checkbox"><input type="checkbox" checked={push} onChange={e=>setPush(e.target.checked)}/>模拟启用微信推送</label><div className="lab-actions"><button disabled={!!busy} onClick={()=>task('模拟发送微信测试',()=>{setNotifyRows(v=>['模拟测试消息：发送与收件演示成功',...v]);setNotice('测试消息已放入下方微信样式预览，并未实际发送。')})}><Bell size={18}/>发送模拟测试</button><button disabled={!!busy||!push} onClick={()=>task('模拟推送日报',()=>{setNotifyRows(v=>['今日重点：小米经营进展值得核对；行业政策提供背景。点击查看来源与研究。',...v]);setNotice('模拟日报已生成；相同事件正式版本会去重。')})}>模拟推送今日简报</button></div><div className="lab-wechat"><h3>微信消息预览</h3>{notifyRows.length?notifyRows.map((n,i)=><article key={i}><strong>投资信息台 · 演示消息</strong><p>{n}</p><small>模拟收件 · 不代表真实微信已接通</small></article>):<p>点击「发送模拟测试」，这里会出现消息。</p>}</div></section>
 <section className="lab-settings"><h2>研究断点与备份</h2><p>演示某次研究中途停止，保留已经完成的章节。</p><div className="lab-actions"><button onClick={()=>{setResumed(false);setNotice('模拟研究暂停：业务与财务已完成，其余4章节待继续。')}}>模拟研究中断</button><button disabled={!!busy} onClick={()=>task('继续未完成章节',()=>{setResumed(true);setNotice('已模拟补齐4章节，没有重复调用已完成章节。')})}>继续模拟研究</button></div><p>{resumed?'示例研究6/6章节完成。':'示例研究2/6章节完成；资料与已完成内容保留。'}</p><div className="lab-actions"><button onClick={()=>{download('仅演示-虚拟账户备份.json',JSON.stringify({demo:true,rows,cash,fx},null,2));setNotice('已下载仅含虚拟数据的JSON演示备份；不是正式SQLite备份。')}}><Download size={18}/>下载虚拟备份</button><button onClick={()=>{setRows(seed.map(h=>({...h})));setCash(50200);setFx(.92);setLedger(true);setReport(null);setTick(0);setQuoteTime('2026-10-05 10:00:00');setImportDone(false);setNotice('已恢复内置演示账户，真实数据库没有变化。')}}>恢复内置虚拟备份</button></div></section></>}
 </>;
}
