import {useState,useEffect} from 'react';
import {ExternalLink,RefreshCw,ChevronDown} from 'lucide-react';
export function NewsFeed({news,disabled,onRefresh,onAnalyze,status,resultJump}:any){
 const [filter,setFilter]=useState('all');const [opened,setOpened]=useState<string|null>(null);const items=news.filter((n:any)=>filter==='all'||n.category===filter);
 useEffect(()=>{if(resultJump?.id.startsWith('news:')){setFilter('all');setOpened(resultJump.id.slice(5));}},[resultJump]);
 useEffect(()=>{
  if(!resultJump?.id.startsWith('news:')||opened!==resultJump.id.slice(5)||filter!=='all')return;
  const frame=requestAnimationFrame(()=>{const node=Array.from(document.querySelectorAll<HTMLElement>('[data-result-id]')).find(n=>n.dataset.resultId===resultJump.id);node?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});node?.focus({preventScroll:true});});
  return()=>cancelAnimationFrame(frame);
 },[resultJump,opened,filter]);
 return <section className="news-feed"><div className="section-title"><h2>公告与财经新闻</h2><button className="text-button" disabled={disabled} onClick={onRefresh}><RefreshCw size={17}/>更新新闻</button></div>{status?.status==='failed'&&<p className="help">{status.message}</p>}<div className="news-filters">{[['all','全部'],['announcement','公司公告'],['official','官方发布'],['media','新闻来源']].map(([key,label])=><button aria-pressed={filter===key} className={filter===key?'reader-selected':''} key={key} onClick={()=>setFilter(key)}>{label}</button>)}</div>
 {items.length?items.map((n:any)=><article key={n.id}><div className="news-meta"><span>{n.category==='announcement'?'公司公告':n.category==='official'?'官方发布':'新闻来源'}</span><span>{n.company||n.publisher}</span><time>{n.published_at?(Number.isNaN(new Date(n.published_at).valueOf())?n.published_at:new Date(n.published_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})):'发布日期未确认'}</time></div><h3>{n.title}</h3>{n.summary&&<><p>{String(n.summary).match(/[^。！？]+[。！？]?/)?.[0]||n.summary}</p>{String(n.summary).match(/[。！？]/)&&String(n.summary).split(/[。！？]/).filter(Boolean).length>1&&<details><summary>展开内容</summary><p className="chapter-text">{n.summary}</p></details>}</>}<a href={n.url} target="_blank" rel="noreferrer">{n.publisher} · 阅读原文<ExternalLink size={14}/></a>{n.verification==='title_only'&&<p className="help">仅获取标题。</p>}<div className="news-actions"><button className="secondary" disabled={disabled&&!n.analysis} onClick={()=>{setOpened(opened===n.id?null:n.id);if(!n.analysis)onAnalyze(n.id)}}>{n.analysis?'查看 AI 分析':'AI 分析'}<ChevronDown size={16}/></button>{!n.analysis&&<small>按需调用，计入预算</small>}</div>{opened===n.id&&(n.analysis?<section className="news-analysis result-target" data-result-id={'news:'+n.id} tabIndex={-1} aria-label={'新闻分析：'+n.title}><h3>关键内容与可能影响</h3><p className="meta">{n.analysis.payload.coverage_note} · AI 推论</p><p className="chapter-text">{n.analysis.payload.summary}</p>{[['support','关注重点'],['risks','风险与反方'],['unknowns','待确认'],['unverified','未核实内容']].map(([key,label])=>n.analysis.payload[key]?.length>0&&<div key={key}><h4>{label}</h4><ul>{n.analysis.payload[key].map((v:any,i:number)=><li key={i}>{typeof v==='string'?v:v.text}</li>)}</ul></div>)}{n.analysis.payload.validation_warnings?.length>0&&<details><summary>核验提示</summary>{n.analysis.payload.validation_warnings.map((v:string,i:number)=><p key={i}>{v}</p>)}</details>}<a href={n.analysis.payload.source_url} target="_blank" rel="noreferrer">核对原文<ExternalLink size={14}/></a></section>:disabled?<p role="status" className="help">正在获取资料并分析，请稍候。</p>:<p className="help">尚未生成分析，可重试前先检查页面错误提示。</p>)}</article>):<p className="muted">暂无资料。更新新闻，或研究关注公司后查看相关来源。</p>}
 </section>;
}
