import {useEffect,useRef,useState} from 'react';
import {scenarioLoss} from './scenario';
import {Check,ChevronRight,ExternalLink,X} from 'lucide-react';
const text=(v:any):string=>typeof v==='string'?v:v?.text||'';
const date=(v:string)=>{if(!v)return '时间未提供';const d=new Date(v);return Number.isNaN(d.valueOf())?v:d.toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});};
function Points({payload}:any){return <>{[['support','支持依据'],['risks','风险与反方'],['unknowns','待确认'],['assumptions','采用的假设']].map(([key,label])=>payload?.[key]?.length>0&&<section key={key}><h3>{label}</h3><ul>{payload[key].map((p:any,i:number)=><li key={i}>{text(p)}{p.reason&&<small>{p.reason}</small>}{p.evidence_ids?.length>0&&<small>来源 {p.evidence_ids.join('、')}</small>}</li>)}</ul></section>)}{payload?.unverified?.length>0&&<details><summary>未核实内容 · {payload.unverified.length} 项</summary><ul>{payload.unverified.map((p:any,i:number)=><li key={i}>{text(p)}{p.reason&&<small>{String(p.reason).replace('未保存为正式研究。','请核对来源。')}</small>}</li>)}</ul></details>}{payload?.facts?.length>0&&<details><summary>资料原文</summary><ul>{payload.facts.map((p:any,i:number)=><li key={i}>{text(p)}<small>{p.evidence_id?'来源 '+p.evidence_id:''} {p.locator||''}</small></li>)}</ul></details>}</>}
export function ReportReader({report,onClose,onFollowup,disabled,amount}:any){
 const p=report.payload||{},sections=p.sections||[];
 const [tab,setTab]=useState((sections.find((s:any)=>s.status==='done')||sections[0])?.key||'overview'),ref=useRef<HTMLElement>(null);
 useEffect(()=>{setTab((sections.find((s:any)=>s.status==='done')||sections[0])?.key||'overview');ref.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});ref.current?.focus({preventScroll:true});},[report.id]);
 const portfolio=report.kind==='portfolio';
 const [drop,setDrop]=useState(10),[fxDrop,setFxDrop]=useState(0);
 const loss=scenarioLoss(p.snapshot,drop,fxDrop);
 const active=sections.find((s:any)=>s.key===tab),body=active?.report;
 const summary=sections.length?(sections.find((s:any)=>s.report?.summary)?.report?.summary||p.summary):p.summary;
 const sentences=String(summary||'').match(/[^。！？]+[。！？]?/g)||[];
 const lead=sentences.slice(0,2).join(''),rest=sentences.slice(2).join('');
 const chapterLabels:Record<string,string>={business:'业务与盈利',financial:'历史财务',events:'最新变化',competition:'行业与同业',valuation:'估值与情景',countercase:'反方与风险'};
 const highlights=[['重点',p.support?.[0]],['风险',p.risks?.[0]],['待核实',p.unknowns?.[0]]].filter(([,v])=>v);
 return <section className="report-reader reading-paper" data-result-id={'report:'+report.id} ref={ref} tabIndex={-1} aria-label="研究报告">
  <div className="reader-top"><span><Check size={16}/>{report.preview?(report.previewFailed?'分析未完成 · 已保留 ':'分析中 · 已完成 ')+p.coverage?.completed_sections+'/'+p.coverage?.total_sections:'已保存'}</span><button className="icon-button" aria-label="关闭报告" onClick={onClose}><X size={19}/></button></div>
  <h2>{p.title||'研究报告'}</h2><p className="meta">截止 {date(p.as_of||report.created_at)}（北京时间）{p.coverage?.completed_sections!=null&&` · 已完成 ${p.coverage.completed_sections}/${p.coverage.total_sections} 章节`}</p>
  {(p.validation_warnings?.length>0||p.unverified?.length>0)&&<p className="help">部分内容待核实，详见「来源与核验」。</p>}
  <div className="reader-summary"><h3>研究摘要</h3><p className="chapter-text">{lead||'报告未提供摘要，请查看章节。'}</p>{rest&&<details><summary>展开摘要</summary><p className="chapter-text">{rest}</p></details>}</div>
  {highlights.length>0&&<div className="reader-takeaways">{highlights.map(([label,v]:any)=><div key={label}><strong>{label}</strong><p>{text(v)}</p></div>)}</div>}
  <div className="reader-layout"><nav className="reader-nav" aria-label="报告章节"><h3>阅读章节</h3>{(portfolio?[{key:'overview',label:'组合判断'},{key:'positions',label:'仓位与贡献'},{key:'scenarios',label:'压力情景'},{key:'risk',label:'历史风险'}]:sections.length?sections:[{key:'overview',label:'研究正文'}]).map((s:any)=><button key={s.key} aria-pressed={tab===s.key} className={tab===s.key?'reader-selected':''} onClick={()=>setTab(s.key)}>{chapterLabels[s.key]||s.label}<ChevronRight size={15}/></button>)}<button aria-pressed={tab==='sources'} className={tab==='sources'?'reader-selected':''} onClick={()=>setTab('sources')}>来源与核验<ChevronRight size={15}/></button></nav>
   <div className="reader-chapter" aria-live="polite">
    {tab==='sources'?<><h3>来源与核验</h3>{(report.evidence||[]).map((e:any)=><p key={e.id}><a href={e.url} target="_blank" rel="noreferrer">来源 {e.id} · {e.title}<ExternalLink size={14}/></a><small>{e.published_at||'发布日期未确认'}</small></p>)}{!(report.evidence||[]).length&&<p className="muted">这份报告没有独立来源链接。</p>}{p.validation_warnings?.map((w:string,i:number)=><p className="help" key={i}>{w}</p>)}{p.unverified?.length>0&&<details><summary>未核实内容 · {p.unverified.length} 项</summary>{p.unverified.map((v:any,i:number)=><p key={i}>{text(v)}{v.reason&&<small>{String(v.reason).replace("未保存为正式研究。","请核对来源。")}</small>}</p>)}</details>}{Number(p.coverage?.unreadable_sources)>0&&<p className="help">未读取资料 {p.coverage.unreadable_sources} 份</p>}{p.verification_note&&<p className="help">{p.verification_note}</p>}</>:
    portfolio&&tab==='positions'?<><h3>本次仓位快照</h3><div className="reader-positions">{(p.snapshot?.positions||[]).map((s:any)=><div key={s.id}><strong>{s.name}</strong><span>{s.weight==null?'仓位待核算':s.weight+'%'}</span><div className="weight-bar"><span style={{width:`${Math.min(100,Math.max(0,Number(s.weight)||0))}%`}}/></div><small>人民币估值 {s.base_value==null?'缺失':amount(s.base_value)} · 盈亏 {amount(s.gain_cny??s.snapshot_gain_cny)}</small></div>)}</div>{!p.snapshot?.positions?.length&&<p>这份报告没有保存持仓快照。</p>}</>:
    portfolio&&tab==='scenarios'?<><h3>压力情景</h3><p className="help">假设变化，不是预测；金额按本次快照计算。</p>{p.risk?.scenarios?.map((s:any,i:number)=><div className="scenario-result" key={i}><span>{s.name}</span><strong>{s.loss_cny==null?'数据不足':amount(s.loss_cny)} 元</strong></div>)}{p.risk?.scenario_note&&<p className="help">{p.risk.scenario_note}</p>}{!p.risk?.scenarios?.length&&<p>暂无可计算情景。</p>}<h3>自定义情景</h3><div className="scenario-inputs"><label>证券下跌（%）<input type="number" min={0} max={100} step={1} value={drop} onChange={e=>setDrop(Number(e.target.value))}/></label><label>港币贬值（%）<input type="number" min={0} max={100} step={1} value={fxDrop} onChange={e=>setFxDrop(Number(e.target.value))}/></label></div><p>预计减少 <strong>{loss==null?'无法计算':amount(loss)+' 元'}</strong></p><p className="help">按冻结快照重算，包含港币现金的汇率影响；不调用 AI。</p></>:
    portfolio&&tab==='risk'?<><h3>历史风险</h3>{p.risk?.warnings?.map((w:string,i:number)=><p key={i}>{w}</p>)}<p>有效共同交易日：{p.risk?.observations??'缺失'}</p><h3>集中度</h3>{[['行业',p.risk?.industry_weights],['报价币种',p.risk?.currency_weights]].map(([label,groups]:any)=><p key={label}>{label}：{Object.entries(groups||{}).map(([k,v])=>`${k} ${v}%`).join('；')||'待核算'}</p>)}{p.risk?.risk_contribution&&<><h3>风险贡献</h3><p className="help">{p.risk.risk_note}</p>{Object.entries(p.risk.risk_contribution).map(([k,v])=><p key={k}>{k} · 日波动贡献 {(Number(v)*100).toFixed(3)}%</p>)}</>}{p.risk?.correlation&&<details><summary>历史相关性</summary><div className="table-scroll"><table><thead><tr><th>证券</th>{Object.keys(p.risk.correlation).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{Object.entries(p.risk.correlation).map(([k,row]:any)=><tr key={k}><th>{k}</th>{Object.keys(p.risk.correlation).map(j=><td key={j}>{row[j]==null?'缺失':Number(row[j]).toFixed(3)}</td>)}</tr>)}</tbody></table></div></details>}</>:
    <><h3>{active?.label||'研究判断'}</h3>{active&&active.status!=='done'&&<p className="help">{active.status==='partial'?'本章部分完成':report.preview?(report.previewFailed?'本章未完成。':'本章正在准备，完成后自动更新。'):'本章尚未完成，可在维护页继续研究。'}</p>}{body?<><p className="chapter-text">{body.summary}</p><Points payload={body}/></>:active?<p>本章暂无内容。</p>:<><p className="chapter-text">{p.summary}</p><Points payload={p}/></>}{p.calculation&&(tab==='valuation'||!sections.length)&&<details><summary>估值计算快照</summary><p>PE {p.calculation.pe??'缺失'} · PB {p.calculation.pb??'缺失'} · 股息率 {p.calculation.dividend_yield??'缺失'}%</p><pre>{JSON.stringify(p.calculation,null,2)}</pre></details>}</>}
   </div>
  </div>
  {!report.preview&&['research','followup'].includes(report.kind)&&<div className="reader-followup"><h3>继续了解</h3><div className="button-row">{['解释简单一点','继续持有，需要注意哪些风险？'].map(q=><button className="secondary" key={q} disabled={disabled} onClick={()=>onFollowup(q)}>{q}</button>)}</div><form className="search-bar" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onFollowup(String(f.get('question')));}}><input name="question" aria-label="追问报告" required maxLength={500} placeholder="你的问题"/><button className="primary" disabled={disabled}>问一问</button></form></div>}
 </section>;
}
