import {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Leaf,ArrowRight,Check,LoaderCircle,RotateCcw,ChevronRight,FileText,AlertCircle} from 'lucide-react';
import './style.css';
import './ResearchDemo.css';
import {FeedbackDock} from './FeedbackDock';
const roles=[{name:'研究规划',detail:'检查资料覆盖，列出关键问题',output:'已确定业务、财务、竞争、估值四条研究线。订单增长存在冲突，新业务资本开支尚缺。',tab:'sources'},{name:'公司研究',detail:'解释业务与财务变化',output:'2025年收入增长25%，但经营现金流仅为利润的55.6%。盈利增长与现金质量需要分别判断。',tab:'financial'},{name:'独立反方',detail:'仅依据模拟原始资料，独立寻找反证',output:'库存周转由60天升至85天。收入增长可能伴随库存和营运资金压力，不能只看利润增速。',tab:'counter'},{name:'综合分析',detail:'对照双方证据，保留分歧',output:'增长改善是支持证据，现金转化和订单冲突仍未解决。总体判断由“增长明确”调整为“增长改善，质量待验证”。',tab:'overview'}];
const chapters=[['overview','结论与变化'],['business','业务结构'],['financial','财务与计算'],['events','最新变化'],['competition','同行比较'],['valuation','估值情景'],['counter','独立反方'],['sources','资料与缺口']];
const financials=[{year:'2023',revenue:80,profit:8,cash:7,capex:4,days:60},{year:'2024',revenue:96,profit:10.56,cash:8.5,capex:5,days:70},{year:'2025',revenue:120,profit:14.4,cash:8,capex:6,days:85}];
const sources=[{name:'A · 模拟年度报告',date:'2025年度',body:'收入120亿港元，净利润14.4亿港元，经营现金流8亿港元，资本开支6亿港元。库存周转85天。业务收入分别为硬件72亿、企业服务36亿、新业务12亿。'}, {name:'B · 模拟经营公告',date:'2026年9月',body:'公告称本期新订单金额同比增长18%，企业服务客户续约率92%。新业务的独立资本开支尚未披露。'}, {name:'C · 模拟媒体摘要',date:'2026年9月',body:'摘要称同一期新订单金额增长8%。与公告中的18%冲突，未找到支持8%的原始材料，不能混用或取平均。'}, {name:'D · 模拟同业样本',date:'模拟同一估值日',body:'示例同业甲：市盈率16倍，净利率14%；示例同业乙：市盈率18倍，净利率11%。业务结构不同，不能直接将同业倍数当作合理价格。'}];
function App(){
 const [scenario,setScenario]=useState('normal'),[mode,setMode]=useState<'quick'|'deep'>('deep'),[stage,setStage]=useState(-1),[busy,setBusy]=useState(false),[result,setResult]=useState(false),[partial,setPartial]=useState(false),[tab,setTab]=useState('overview'),[notice,setNotice]=useState(''),[height,setHeight]=useState(0),[growth,setGrowth]=useState(10),[margin,setMargin]=useState(12),[multiple,setMultiple]=useState(15),[source,setSource]=useState<number|null>(null);
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null),reportRef=useRef<HTMLElement>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 function reveal(){reportRef.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});reportRef.current?.focus({preventScroll:true});}
 function start(next:'quick'|'deep',resume=false){
  if(timer.current)clearTimeout(timer.current);setMode(next);setBusy(true);setNotice('');setSource(null);
  if(!resume){setResult(false);setPartial(false);setTab('overview')}
  let step=resume?2:0;setStage(step);
  function advance(){timer.current=setTimeout(()=>{
    if(next==='quick'){setStage(4);setBusy(false);setResult(true);setNotice('快速更新已完成 · 模拟结果');return;}
    if(scenario==='interrupt'&&!resume&&step===1){setBusy(false);setStage(2);setPartial(true);setResult(true);setNotice('模拟分析中断，已保留完成内容');return;}
    step++;setStage(step);if(step===4){setBusy(false);setPartial(false);setResult(true);setNotice('深度研究已完成 · 模拟结果');}else advance();
  },1300)}advance();
 }
 function reset(){if(timer.current)clearTimeout(timer.current);setBusy(false);setResult(false);setPartial(false);setStage(-1);setTab('overview');setScenario('normal');setMode('deep');setNotice('');setGrowth(10);setMargin(12);setMultiple(15);setSource(null)}
 const projectedRevenue=120*(1+growth/100),profit=projectedRevenue*margin/100,eps=profit/10,value=eps*multiple,delta=(value/18-1)*100;
 return <div className="shell rd-shell" style={{'--feedback-clearance':`${height}px`} as React.CSSProperties}>
 <aside className="sidebar"><a className="brand" href="#" onClick={e=>e.preventDefault()}><Leaf/><span>投资信息台</span></a><nav aria-label="演示导航"><button className="selected" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}>研究体验<ChevronRight size={18}/></button><button disabled={!result} onClick={reveal}>查看报告<FileText size={18}/></button></nav><p className="rd-side-note">研究质量 Demo<br/>所有公司与资料均为虚构</p><button onClick={reset}><RotateCcw size={17}/>重置演示</button></aside>
 <main><FeedbackDock notice={notice} progress={busy?(mode==='quick'?'正在整理最新变化 · 模拟流程':roles[Math.min(stage,3)].name+'进行中 · 模拟流程'):''} onNoticeClose={()=>setNotice('')} onErrorClose={()=>{}} onViewResult={result?reveal:undefined} onHeight={setHeight}/>{height>0&&<div className="feedback-spacer" style={{height}}/>}
 <header className="rd-top"><span>公司研究 / 体验预览</span><strong>模拟数据 · 不连接真实服务</strong></header>
 <div className="page-heading"><h1>研究，不止一个结论。</h1><p>看懂业务，核对数字，再听听反方。</p></div>
 <section className="rd-company"><div><span className="rd-caption">虚构公司 · DEMO</span><h2>示例科技公司</h2><p>智能硬件与企业服务 · 模拟现价 HK$18.00</p></div><div className="rd-actions"><button className="secondary" disabled={busy} onClick={()=>start('quick')}>快速更新</button><button className="primary" disabled={busy} onClick={()=>start('deep')}>深度研究<ArrowRight size={18}/></button></div></section>
 <div className="rd-controls"><label>体验场景<select value={scenario} disabled={busy} onChange={e=>{setScenario(e.target.value);setResult(false);setPartial(false);setStage(-1);setNotice('')}}><option value="normal">正常研究</option><option value="missing">资料不足</option><option value="interrupt">分析中断</option></select></label><p>快速更新约2秒，深度研究约6秒。异常场景用于深度研究；不产生费用。</p></div>
 <section className="rd-workflow"><div className="section-title"><h2>四个研究角色</h2><span className="meta">模拟分工，不是真实 agent 执行</span></div><div className="rd-role-list">{roles.map((role,i)=>{const done=mode==='deep'&&stage>i,active=busy&&mode==='deep'&&stage===i;return <div className={'rd-role '+(active?'rd-role-active':'')} key={role.name}><div className="rd-role-icon">{done?<Check size={20}/>:active?<LoaderCircle className="spin" size={20}/>:<span>{i+1}</span>}</div><div><h3>{role.name}<small>{done?'已完成':active?'进行中':partial&&i>1?'未完成':mode==='quick'&&stage>=0?'本次不运行':'等待开始'}</small></h3><p>{role.detail}</p>{done&&<details><summary>查看角色结果</summary><p>{scenario==='missing'&&i>0?'收入和库存变化已记录；现金流资料不足，不形成现金质量结论。订单来源冲突和分部资本开支仍需补查。':role.output}</p><button className="text-button" onClick={()=>{setTab(role.tab);if(result)reveal()}}>阅读对应内容<ChevronRight size={15}/></button></details>}</div></div>})}</div></section>
 {!result&&<div className="rd-empty"><FileText size={26}/><p>选择上方研究方式，体验生成过程和报告。</p></div>}
 {result&&<section ref={reportRef} tabIndex={-1} className="reading-paper report-reader rd-report" aria-label="模拟研究报告"><div className="reader-top"><span>{partial?<AlertCircle size={17}/>:<Check size={17}/>} {partial?'部分完成 · 2/4角色':mode==='quick'?'快速更新':'深度研究'}</span><span>模拟截至 2026/10/05</span></div><h2>示例科技公司 · {mode==='quick'?'最新变化':'研究报告'}</h2>
 {partial&&<div className="rd-warning"><strong>分析中断，已完成内容保留</strong><p>规划与公司研究已完成，独立反方及综合分析尚未完成。下面是暂存结果，不是最终结论。</p><button className="secondary" disabled={busy} onClick={()=>start('deep',true)}>继续模拟分析</button></div>}
 <div className="reader-summary"><h3>{partial?'暂存摘要':'关键结论'}</h3><p>{scenario==='missing'?'收入增长改善，现金流资料不足，暂不判断增长是否转化为现金。':'收入增长改善，但现金回收尚未跟上。下一步重点是验证增长质量，而不是只看增速。'}</p></div>
 {!partial&&<div className="reader-takeaways"><div><strong>判断变化</strong><p>从“增长明确”调整为“增长改善，现金质量待验证”。</p></div><div><strong>主要风险</strong><p>库存周转变慢；{scenario==='missing'?'现金流资料不足':'经营现金流低于利润'}；新订单增长出现来源冲突。</p></div><div><strong>需要观察</strong><p>下一期经营现金流、库存天数、服务续约率与订单口径。</p></div></div>}
 {scenario==='missing'&&<div className="rd-warning"><strong>资料覆盖不足</strong><p>缺少2025年现金流明细及分部资本开支。现金流数字仅作为演示数据，不作为本次证据；自由现金流判断暂不提供。</p></div>}
 {mode==='quick'?<div className="rd-quick"><h3>这次发生了什么</h3><p>模拟9月公告：企业服务续约率升至92%，新订单金额增长18%。另一来源称订单增长8%，口径尚未核实。</p><h3>对原判断的影响</h3><p>服务业务稳定性得到支持，但订单冲突未解决，尚不足以改变整体风险判断。</p><h3>下一次复查</h3><ul><li>核对新订单统计范围与比较期间。</li><li>检查新增订单是否转化为现金回款。</li></ul><button className="text-button" onClick={()=>start('deep')}>展开深度研究<ArrowRight size={16}/></button></div>:<div className="reader-layout"><nav className="reader-nav" aria-label="模拟报告章节">{chapters.map(([key,label])=><button key={key} className={tab===key?'reader-selected':''} aria-pressed={tab===key} disabled={partial&&['valuation','counter','overview'].includes(key)} onClick={()=>{setTab(key);setSource(null)}}>{label}<ChevronRight size={15}/></button>)}</nav><div className="reader-chapter">
 {tab==='overview'&&<><h3>{partial?'公司研究暂存内容':'双方证据与综合判断'}</h3><p>支持证据：收入同比增长25%，企业服务占比30%，续约率提升。</p>{!partial&&<p>反方证据：库存天数增加，{scenario!=='missing'&&'利润未充分转化为现金，'}订单增长来源冲突。</p>}<p>{partial?'公司研究已暂存，综合判断等待其余角色完成。':'综合判断：维持观察，优先核实现金质量。这里演示证据如何改变判断，不提供买卖指令。'}</p></>}
 {tab==='business'&&<><h3>收入来自哪里</h3>{[['智能硬件',72,60],['企业服务',36,30],['新业务',12,10]].map(([name,revenue,weight])=><div className="rd-segment" key={name}><div><strong>{name}</strong><span>{revenue}亿港元 · {weight}%</span></div><div className="rd-bar"><span style={{width:weight+'%'}}/></div></div>)}<p>硬件仍决定收入规模，服务业务提供更稳定的收入。分部利润与资本开支缺失，不能据此判断哪项业务贡献最多利润。</p></>}
 {tab==='financial'&&<><h3>三年财务对照</h3><p className="meta">全部虚构 · 金额单位：亿港元</p><div className="table-scroll"><table><thead><tr><th>年度</th><th>收入</th><th>净利润</th><th>经营现金流</th><th>资本开支</th></tr></thead><tbody>{financials.map(f=><tr key={f.year}><td>{f.year}</td><td>{f.revenue}</td><td>{f.profit}</td><td>{scenario==='missing'&&f.year==='2025'?'未取得':f.cash}</td><td>{f.capex}</td></tr>)}</tbody></table></div><p>2025年收入增长25%，净利润率12%。{scenario==='missing'?'现金流明细未取得，暂停现金质量结论。':'经营现金流 / 净利润 = 55.6%，自由现金流为2亿港元。'}</p><details><summary>展开计算依据</summary><p>收入增长：(120 ÷ 96 − 1) × 100% = 25%</p><p>利润率：14.4 ÷ 120 × 100% = 12%</p>{scenario!=='missing'&&<><p>现金转化：8 ÷ 14.4 × 100% ≈ 55.6%</p><p>自由现金流：8 − 6 = 2亿港元</p></>}<button className="text-button" onClick={()=>{setTab('sources');setSource(0)}}>查看模拟输入来源</button></details></>}
 {tab==='events'&&<><h3>最新经营变化</h3><p>9月模拟经营公告：服务续约率92%，新订单金额增长18%。</p><div className="rd-warning"><strong>来源冲突：18% 与 8%</strong><p>公告与媒体摘要给出不同数字。优先保留公告口径，同时标记待核实，不取平均。</p></div><p>需要核对订单定义、期间及是否包含取消订单。指标改善不等于利润或现金立即改善。</p></>}
 {tab==='competition'&&<><h3>同行是参考，不是答案</h3><div className="table-scroll"><table><thead><tr><th>虚构公司</th><th>市盈率</th><th>净利率</th></tr></thead><tbody><tr><td>示例科技</td><td>12.5倍</td><td>12%</td></tr><tr><td>示例同业甲</td><td>16倍</td><td>14%</td></tr><tr><td>示例同业乙</td><td>18倍</td><td>11%</td></tr></tbody></table></div><p>服务占比、资本投入和增长预期不同。估值较低可能代表机会，也可能反映现金质量与业务风险。</p></>}
 {tab==='valuation'&&<><h3>价格背后的假设</h3><p>简化市盈率情景，全部为虚构输入。拖动假设可即时复算。</p><div className="rd-sliders"><label>收入增长 <strong>{growth}%</strong><input type="range" min="-20" max="40" value={growth} onChange={e=>setGrowth(Number(e.target.value))}/></label><label>净利率 <strong>{margin}%</strong><input type="range" min="4" max="20" value={margin} onChange={e=>setMargin(Number(e.target.value))}/></label><label>市盈率 <strong>{multiple}倍</strong><input type="range" min="8" max="25" value={multiple} onChange={e=>setMultiple(Number(e.target.value))}/></label></div><div className="rd-valuation"><span>假设对应价格</span><strong>HK${value.toFixed(2)}</strong><p>相对模拟现价18港元：{delta>=0?'+':''}{delta.toFixed(1)}%</p></div><details><summary>查看完整算式与单位</summary><p>收入：120 × (1 + {growth}%) = {projectedRevenue.toFixed(2)}亿港元</p><p>利润：{projectedRevenue.toFixed(2)} × {margin}% = {profit.toFixed(2)}亿港元</p><p>总股数假设10亿股；EPS = {profit.toFixed(2)} ÷ 10 = {eps.toFixed(3)}港元/股</p><p>价格 = EPS × {multiple}倍 = {value.toFixed(2)}港元</p></details><p className="help">未计分红、稀释及净债务调整；这是假设敏感性演示，不是预测。</p></>}
 {tab==='counter'&&<><h3>独立反方提出的问题</h3><p className="meta">模拟交付：该角色先读模拟原始资料，不先读公司研究结论。</p><ul><li>收入增长是否由渠道库存积累推动？库存周转从60天升至85天。</li><li>{scenario==='missing'?'现金流明细未取得，暂不能验证利润是否转化为现金。':'利润增长为何没有变成同等现金流？需区分回款延后与持续性问题。'}</li><li>新业务缺少资本开支披露，盈利增长可能低估现金投入。</li></ul><h3>论点失效条件</h3><p>若后续两期库存继续升高、现金转化持续低于60%，需重新评估“增长质量改善”的论点。60%是演示观察阈值，不是行业标准。</p></>}
 {tab==='sources'&&<><h3>资料覆盖与待核实</h3><ul><li>已覆盖：三年收入与利润、业务收入结构、经营公告、同业样本。</li><li>来源冲突：新订单增长18%与8%，尚未完成口径核对。</li><li>资料缺口：分部利润与分部资本开支。{scenario==='missing'&&'另外缺少2025年现金流明细。'}</li></ul><h3>模拟来源说明</h3>{sources.map((s,i)=><button className="rd-source" key={s.name} aria-expanded={source===i} onClick={()=>setSource(source===i?null:i)}><span>{s.name}<small>{s.date} · 点击查看虚构原文</small></span><ChevronRight size={17}/></button>)}{source!==null&&<div className="rd-source-content"><h4>{sources[source].name}</h4><p>{scenario==='missing'&&source===0?'模拟可得材料：收入120亿港元，净利润14.4亿港元，资本开支6亿港元，库存周转85天。业务收入分别为硬件72亿、企业服务36亿、新业务12亿。经营现金流明细未取得。':sources[source].body}</p><small>演示材料，无真实公告或外部链接。</small></div>}</>}
 </div></div>}
 </section>}
 <footer>模拟数据 · 不连接真实服务 · 所有进度和研究结论均用于体验演示</footer>
 </main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
